### ISSUE TITLE
can not run program

### ISSUE THREAD

**Issue by maxt** [tulskiy/musique#2]
Starting DBManager
Loading playlist 0
Loading playlist 1
java.lang.IllegalArgumentException: Invalid SortKey
        at javax.swing.DefaultRowSorter.setSortKeys(DefaultRowSorter.java:288)
        at com.tulskiy.musique.gui.playlist.PlaylistPanel.<init>(PlaylistPanel.java:111)
        at com.tulskiy.musique.gui.MainWindow.<init>(MainWindow.java:42)
        at com.tulskiy.musique.system.Application.start(Application.java:110)
        at com.tulskiy.musique.system.Main.main(Main.java:30)

**Comment by tulskiy** [comment]
fixed, try latest version from git.
